# Generated by Django 4.1.1 on 2022-10-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Subject',
            new_name='write',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='psw',
            new_name='password',
        ),
    ]
